#!/bin/bash


generate_api() {
  rm -rf "$1"

  mkdir "$1"

  java -jar openapi-generator-cli.jar generate \
    -i 'https://app.iconik.io/docs/assets/spec/' \
    -g python \
    -o "$1"
}


generate_api "openapi_sdk"
